name: CI-macOS

# Controls when the action will run. 
# Triggers the workflow on pull request events but only for the master branch.
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 15

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Show environment info
        run: |
          sw_vers
          xcodebuild -version
          xcrun simctl list devices

      - name: List available Xcode schemes (debugging)
        run: xcodebuild -list

      - name: Build app
        run: |
          echo "🚀 Starting xcodebuild"
          set -o pipefail && xcodebuild \
            -scheme "CI" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' \
            build | tee xcodebuild.log | xcpretty

      - name: Run Unit Tests
        run: |
            echo "🧪 Running Unit Tests"
            set -o pipefail && xcodebuild \
            -scheme "CI" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            test | tee xctest.log | xcpretty

      - name: Upload raw logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-logs
          path: |
            xcodebuild.log
            xctest.log